/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobileshop;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Toufique Hasan
 */
public final class ProductInfo extends javax.swing.JFrame {

    /**
     * Creates new form ProductInfo
     */
    public ConnectDB conn = new ConnectDB();
    public Connection conx = null;
    public int _success = 0;
    
    public ProductInfo() {
        initComponents();
        showDate();
        Fillcombo();
        DealerCombo();
        setLocationRelativeTo(null);
        
        String s = "";
        double d;
        for (int i = 1; i <= 12; i++) {
            d = Math.random() * 10;
            s = s + ((int)d);
            if (i % 4 == 0 && i != 12) {
                s = s;
            }
        }
        productid.setText(s);
    }
    
    public void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MMM-yyyy");
        entrydate.setText(s.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        productid = new javax.swing.JTextField();
        entrydate = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        daycmb = new javax.swing.JComboBox();
        monthcmb = new javax.swing.JComboBox();
        yearcmb = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        available = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        categorycombo = new javax.swing.JComboBox();
        NewButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        dealercmb = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Information");

        jLabel10.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toufique Hasan\\Documents\\NetBeansProjects\\MobileShop\\src\\mobileshop\\product-logo.png")); // NOI18N
        jLabel10.setText("PRODUCT INFORMATION");

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel1.setText("Product ID");

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel2.setText("Brand");

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel3.setText("Entry Date");

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel4.setText("Model");

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel6.setText("Description");

        productid.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N

        entrydate.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N

        brand.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N

        model.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N

        description.setColumns(20);
        description.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        daycmb.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        daycmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        monthcmb.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        monthcmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        yearcmb.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        yearcmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel7.setText("MFG DT");

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel8.setText("Price");

        price.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        available.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        available.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel11.setText("Quantity");

        quantity.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N

        SubmitButton.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        SubmitButton.setLabel("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        categorycombo.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        categorycombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        NewButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toufique Hasan\\Documents\\NetBeansProjects\\MobileShop\\src\\mobileshop\\new-logo.png")); // NOI18N
        NewButton.setToolTipText("New ");
        NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButtonActionPerformed(evt);
            }
        });

        SearchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toufique Hasan\\Documents\\NetBeansProjects\\MobileShop\\src\\mobileshop\\search-logo.png")); // NOI18N
        SearchButton.setToolTipText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel12.setText("Dealer");

        dealercmb.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        dealercmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel9.setText("Availability");

        jLabel13.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel13.setText("Category");

        backbutton.setBackground(new java.awt.Color(204, 255, 204));
        backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toufique Hasan\\Documents\\NetBeansProjects\\MobileShop\\src\\mobileshop\\back-icon.png")); // NOI18N
        backbutton.setToolTipText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(73, 73, 73))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entrydate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(model, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categorycombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(available, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(daycmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(monthcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dealercmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(brand)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SubmitButton)
                        .addGap(49, 49, 49)
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewButton)
                            .addComponent(SearchButton))
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(productid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(entrydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(dealercmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categorycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(daycmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yearcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(monthcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewButton)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(available, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitButton)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32))
                    .addComponent(backbutton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        SaveData();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButtonActionPerformed
        // TODO add your handling code here:
        NewData();
    }//GEN-LAST:event_NewButtonActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        this.dispose();         
    }//GEN-LAST:event_backbuttonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        SearchProduct ah = new SearchProduct();
        ah.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProductInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JComboBox available;
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField brand;
    private javax.swing.JComboBox categorycombo;
    private javax.swing.JComboBox daycmb;
    private javax.swing.JComboBox dealercmb;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField entrydate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField model;
    private javax.swing.JComboBox monthcmb;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productid;
    private javax.swing.JTextField quantity;
    private javax.swing.JComboBox yearcmb;
    // End of variables declaration//GEN-END:variables

    private void SaveData() {
        conx = conn.getConnection();
        
        try{
             String sql = "{call insert_into_PRODUCT_INFO(?,?,?,?,?,?,?,?,?,?,?)}";
            //OraclePreparedStatement pst = (OraclePreparedStatement) conn.conn;
            PreparedStatement pst = conx.prepareCall(sql);
            
            if (productid.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Product Id","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (entrydate.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Entry Date","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (brand.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter brand","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (model.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter model","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (price.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Price","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (quantity.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Quantity","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String DobDate = "";
            DobDate = daycmb.getSelectedItem().toString() + "-" + monthcmb.getSelectedItem().toString() + "-" + yearcmb.getSelectedItem().toString();
            
            pst.setString(1, productid.getText());
            pst.setString(2, entrydate.getText());
            pst.setString(3, (String) dealercmb.getSelectedItem());
            pst.setString(4, brand.getText());
            pst.setString(5, model.getText());
            pst.setString(6, (String) categorycombo.getSelectedItem());
            pst.setString(7, description.getText());
            pst.setString(8, DobDate);
            pst.setString(9, price.getText());
            pst.setString(10, (String) available.getSelectedItem());
            pst.setString(11, quantity.getText());
            
             _success = pst.executeUpdate();
             JOptionPane.showMessageDialog(this,"Successfully Submitted !!!","Record",JOptionPane.INFORMATION_MESSAGE);
             NewData();
            //rs = (OracleResultSet) pst.executeUpdate(sql);

        }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    
    private void Fillcombo(){
        conx = conn.getConnection();
        try{
            String sql = "select * from CATEGORY_INFO";
            PreparedStatement pst = conx.prepareCall(sql);
            ResultSet rs = pst.executeQuery(sql);
            
            while(rs.next()){
                String name = rs.getString("CATEGORYNAME");
                categorycombo.addItem(name);
            }
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }

    private void NewData() {
        brand.setText("");
        model.setText("");
        description.setText("");
        price.setText("");
        quantity.setText("");
        
    }

    private void DealerCombo() {
        conx = conn.getConnection();
        try{
            String sql = "select * from DEALER_INFO";
            PreparedStatement pst = conx.prepareCall(sql);
            ResultSet rs = pst.executeQuery(sql);
            
            while(rs.next()){
                String name = rs.getString("DealerName");
                dealercmb.addItem(name);
            }
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }

}
